" pathogen bundles
filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()
filetype plugin indent on
set mouse=a
set ttymouse=xterm2
set number
syntax enable
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=16
colorscheme solarized
