" pathogen bundles
filetype off
call pathogen#infect()
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()
filetype plugin indent on
set mouse=a
set ttymouse=xterm2
set number
syntax enable
set background=dark
let g:solarized_termtrans=1
" let g:solarized_termcolors=16
colorscheme solarized

" Yank text to the OS X clipboard
noremap <leader>y "*y
noremap <leader>yy "*Y

" Preserve indentation while pasting text from the OS X clipboard
noremap <leader>p :set paste<CR>:put  *<CR>:set nopaste<CR>

